# https://cypress.tips/courses/cypress-plugins/lessons/m3
stages:
  - build
  - test

## Set environment variables for folders in "cache" job settings for npm modules and Cypress binary
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# Cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - .npm/*
    - cache/Cypress
    - node_modules

install:
  image: cypress/base:16.14.2-slim
  stage: build
  script:
    # install dependencies
    - npm ci

test:
  image: cypress/base:16.14.2-slim
  stage: test
  parallel: 3
  script:
    - npm start &
    - npx cypress run --env split=true