name: ci
on: push
jobs:
  tests:
    runs-on: ubuntu-20.04
    # run 3 copies of the current job in parallel
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3

      - name: Run split Cypress tests 🧪
        uses: cypress-io/github-action@v5
        # pass the machine index and the total number
        with:
          start: npm start
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
